CREATE TABLE scan_run (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    target_id BIGINT UNSIGNED NOT NULL,
    status ENUM('queued', 'running', 'done', 'failed') NOT NULL DEFAULT 'queued',
    stage VARCHAR(32) NOT NULL DEFAULT 'queued',
    stage_message VARCHAR(255) NULL,
    context_json JSON NULL,
    wildcard_ips_json JSON NULL,
    notes_json JSON NULL,
    ips_json JSON NULL,
    names_json JSON NULL,
    error_text TEXT NULL,
    dns_threads INT UNSIGNED NOT NULL DEFAULT 40,
    http_timeout INT UNSIGNED NOT NULL DEFAULT 10,
    probe_http TINYINT(1) NOT NULL DEFAULT 1,
    use_passive TINYINT(1) NOT NULL DEFAULT 1,
    use_reverse_ip TINYINT(1) NOT NULL DEFAULT 1,
    try_axfr TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    CONSTRAINT fk_scan_run_target FOREIGN KEY (target_id) REFERENCES scan_target (id) ON DELETE CASCADE,
    KEY idx_scan_run_status_stage (status, stage),
    KEY idx_scan_run_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
